apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata: 
  name: nodes-read-kul
subjects: 
- kind: User
  name: kul
  apiGroup: rbac.authorization.k8s.io
roleRef: 
  kind: ClusterRole
  name: nodes-list-kul 
  apiGroup: rbac.authorization.k8s.io
