apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-nodes-kul
  namespace: kul
subjects:
- kind: User
  name: kul
  apiGroup: rbac.authorization.k8s.io
- kind: User
  name: manish
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: nodes-list-kul
  apiGroup: rbac.authorization.k8s.io
