apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods-kul
  namespace: default
subjects:
- kind: User
  name: kul
  apiGroup: rbac.authorization.k8s.io
- kind: User
  name: manish
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-read
  apiGroup: rbac.authorization.k8s.io
